import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { Toaster as Sonner } from "~/components/ui/sonner";
import { cn } from "~/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "web course",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "dark min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        {children}
        <Sonner richColors />
      </body>
    </html>
  );
}
